Async-related changes, mostly to foster communications between a (full python3) host and one or more Micropython-based microcontrollers.
peterhinch/micropython-msgpack pull request #5
Opened 2024-08-04 22:43 UTC by bapowell

- Changed uasyncio to asyncio.
  - Provided a new example, asyntest_py3_serial.py, to demonstrate running under full python3.
- Changed as_load.py.
  - Added missing _file() function.
  - Added 'observer' option for aload.
- Added as_loader.py.
  - New aloader class, which offers the same functionality as aload, but in a cleaner, objected-oriented manner.

2024-08-05 09:11 UTC, peterhinch commented
Thanks for that, it looks like a useful enhancement. I will study this later in the week.

2024-08-05 12:46 UTC, peterhinch commented
Re running under CPython. Please could you share the motivation for this. For context please see https://github.com/peterhinch/micropython-msgpack/issues/3#issuecomment-1506506727 where I outline my reasons for not going down this route.

2024-08-05 12:58 UTC, bapowell commented
Yours supports asyncio streams (aload), and it works with no change whatsoever between CPython and Micropython. So I'm able to use the same library for both code bases: host vs microcontroller, with serial comms between them.

2024-08-06 16:30 UTC, peterhinch commented on asyntest.py
A better way to detect the platform is
```py
from sys import platform
if platform == "pyboard":
    uart = UART(4, 9600)
elif platform == "rp2:
    uart = UART(0, baudrate=9600, tx=Pin(0), rx=Pin(1))  # Pi Pico (link pins 0 and 1)
else:
    raise OSError(f"Unknown platform {platform}") 
```
Or other exception if you think OSError is wrong. This detection method is more robust and easily extensible e.g. to ESP32.

2024-08-06 16:33 UTC, peterhinch requested changes
Aside from my comment on platform detection I like this. Nice work.

2024-08-07 02:25 UTC, bapowell commented on asyntest.py
I agree that's a much better way.
I just pushed a commit, per your suggestion. I also included esp32 (and tested it) while I was at it.

2024-08-07 07:56 UTC, merged

2024-08-07 07:57 UTC, peterhinch commented
Thank you.

2024-08-07 10:02 UTC, peterhinch commented
Thanks also for pointing out the bug :)

I've pushed an update with the following changes:
1. The package may be installed using `mpremote`.
2. `README.md` explains installation options and lists files with their purpose.
3. Bug fixed. My editor is configured to run Black on changed files, so there is PEP8 formatting.

2025-06-20 17:07 UTC, peterhinch commented
@bapowell In case you're still following this project, I'm planning a significant upgrade. I've pushed my current work to a branch `modular-extnsions`.

The objectives are in the docs, but some of the major changes are:
* Simplify creation of extensions. Each extension of a built-in now has an individual very simple module.
* Remove the original async code in favour of your `ALoader`.
* Asynchronous decode now uses an asynchronous iterator.
* The `Observer` object can now be any callable and its incoming data includes a delimiter.

Sadly it's a breaking change for async users and creators of extensions.

Comments welcome.

2025-06-21 12:34 UTC, bapowell commented
Those all sound like good changes, Peter.

I skimmed the commits in your `modular-extensions` branch, and don't see anything that's confusing or concerning.

Breaking changes, yes, but shouldn't be terribly difficult for users to refactor their code accordingly.

2025-06-22 13:49 UTC, peterhinch commented
Thanks for the feedback. I'm still doing a few minor code simplifications but I will release soon.